# Generated by Django 2.0.6 on 2018-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
