# Generated by Django 2.0.6 on 2018-08-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180818_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cal_date',
            new_name='date',
        ),
    ]
