# Generated by Django 2.0.6 on 2018-08-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180819_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
