# Generated by Django 2.0.6 on 2018-08-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('meal_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.MealPlans')),
                ('recipes', models.ManyToManyField(to='recipes.Recipe')),
            ],
        ),
    ]
