# Generated by Django 2.0.6 on 2018-08-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20180819_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
    ]
